language: python

python:
  - "3.12"

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov

script:
  - pytest --cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
